/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_embeddedunveiled_serial_internal_SerialComBluetoothJNIBridge */

#ifndef _Included_com_embeddedunveiled_serial_internal_SerialComBluetoothJNIBridge
#define _Included_com_embeddedunveiled_serial_internal_SerialComBluetoothJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComBluetoothJNIBridge
 * Method:    listBluetoothAdaptorsWithInfo
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_embeddedunveiled_serial_internal_SerialComBluetoothJNIBridge_listBluetoothAdaptorsWithInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
