/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge */

#ifndef _Included_com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge
#define _Included_com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge
 * Method:    readLatch
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge_readLatch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge
 * Method:    writeLatch
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge_writeLatch
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge
 * Method:    getPartNumber
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge_getPartNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge
 * Method:    getDeviceProductString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge_getDeviceProductString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge
 * Method:    getDeviceSerialNumber
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge_getDeviceSerialNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge
 * Method:    getDeviceInterfaceString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComCP210xRuntimeJNIBridge_getDeviceInterfaceString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
