/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge */

#ifndef _Included_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
#define _Included_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
 * Method:    listHIDdevicesWithInfo
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_listHIDdevicesWithInfo
=======
 * Method:    initNativeLib
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_initNativeLib
>>>>>>> upstream/master
  (JNIEnv *, jobject);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
<<<<<<< HEAD
 * Method:    openHidDevice
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_openHidDevice
=======
 * Method:    openHidDeviceByPath
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_openHidDeviceByPath
>>>>>>> upstream/master
  (JNIEnv *, jobject, jstring);
=======
 * Method:    listUSBHIDdevicesWithInfo
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_listUSBHIDdevicesWithInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    openHidDeviceByUSBAttributes
 * Signature: (IILjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_openHidDeviceByUSBAttributes
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint, jint);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    openHidDeviceByPathR
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_openHidDeviceByPathR
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    closeHidDeviceR
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_closeHidDeviceR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    createBlockingHIDIOContextR
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_createBlockingHIDIOContextR
  (JNIEnv *, jobject);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    unblockBlockingHIDIOOperationR
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_unblockBlockingHIDIOOperationR
  (JNIEnv *, jobject, jlong);
>>>>>>> upstream/master

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    destroyBlockingIOContextR
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_destroyBlockingIOContextR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
<<<<<<< HEAD
 * Method:    getReportDescriptorSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getReportDescriptorSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    writeOutputReport
 * Signature: (JB[B)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_writeOutputReport
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray);
=======
 * Method:    writeOutputReport
=======
 * Method:    writeOutputReportR
>>>>>>> upstream/master
 * Signature: (JB[BI)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_writeOutputReportR
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray, jint);
>>>>>>> upstream/master

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    readInputReportR
 * Signature: (J[BIJ)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_readInputReportR
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    readInputReportWithTimeoutR
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_readInputReportWithTimeoutR
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
 * Method:    sendFeatureReport
<<<<<<< HEAD
 * Signature: (JB[B)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_sendFeatureReport
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray);
=======
=======
 * Method:    sendFeatureReportR
>>>>>>> upstream/master
 * Signature: (JB[BI)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_sendFeatureReportR
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray, jint);
>>>>>>> upstream/master

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
 * Method:    getFeatureReport
<<<<<<< HEAD
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getFeatureReport
  (JNIEnv *, jobject, jlong, jbyteArray);
=======
=======
 * Method:    getFeatureReportR
>>>>>>> upstream/master
 * Signature: (JB[BI)I
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getFeatureReportR
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray, jint);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    listHIDdevicesWithInfoR
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_listHIDdevicesWithInfoR
  (JNIEnv *, jobject);
>>>>>>> upstream/master

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    getManufacturerStringR
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getManufacturerStringR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    getProductStringR
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getProductStringR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    getSerialNumberStringR
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getSerialNumberStringR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
 * Method:    getIndexedStringR
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getIndexedStringR
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
<<<<<<< HEAD
=======
 * Method:    getReportDescriptor
 * Signature: (J)[B
=======
 * Method:    findDriverServingHIDDeviceR
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
>>>>>>> upstream/master
 */
JNIEXPORT jstring JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_findDriverServingHIDDeviceR
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/master
=======
 * Method:    findDriverServingHIDDevice
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
=======
 * Method:    flushInputReportQueueR
 * Signature: (J)I
>>>>>>> upstream/master
 */
JNIEXPORT jint JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_flushInputReportQueueR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
>>>>>>> upstream/master
 * Method:    listUSBHIDdevicesWithInfo
 * Signature: (I)[Ljava/lang/String;
=======
 * Method:    getReportDescriptorR
 * Signature: (J)[B
>>>>>>> upstream/master
 */
JNIEXPORT jbyteArray JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getReportDescriptorR
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge
<<<<<<< HEAD
 * Method:    openHidDeviceByUSBAttributes
<<<<<<< HEAD
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_openHidDeviceByUSBAttributes
  (JNIEnv *, jobject, jint, jint, jstring);
=======
 * Signature: (IILjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_openHidDeviceByUSBAttributes
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint, jint);
>>>>>>> upstream/master
=======
 * Method:    getPhysicalDescriptorR
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_embeddedunveiled_serial_internal_SerialComHIDJNIBridge_getPhysicalDescriptorR
  (JNIEnv *, jobject, jlong);
>>>>>>> upstream/master

#ifdef __cplusplus
}
#endif
#endif
